home:
  path: /
  controller: App\Controller\HomeController::index
about:
  path: /about
  controller: App\Controller\AboutController::about
#index:
#    path: /
#    controller: App\Controller\DefaultController::index
